# Application Basic Setting
spring.application.name=jsl26tp

# Setting Server PORT
server.port=8090

# Connection Setting Of MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/jsl26tp?serverTimezone=UTC
spring.datasource.username=jsl26
spring.datasource.password=1234

# Setting MyBatis
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.jsl26tp.jsl26tp.auth.domain,com.jsl26tp.jsl26tp.toilet.domain,com.jsl26tp.jsl26tp.review.domain,com.jsl26tp.jsl26tp.report.domain,com.jsl26tp.jsl26tp.inquiry.domain
mybatis.configuration.map-underscore-to-camel-case=true

# Setting Thymeleaf
spring.thymeleaf.cache=false

# Setting Encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

app.upload.path=/Users/kizuna/uploads